events {}

http {
    upstream orderservice {
        server orderservice-api-1:8080;
        server orderservice-api-2:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://orderservice;
        }
    }
}